Refactor test

diff --git a/.github/workflows/push.yaml b/.github/workflows/push.yaml
--- a/.github/workflows/push.yaml
+++ b/.github/workflows/push.yaml
@@ -12,7 +12,7 @@ jobs:
             - name: check test completeness
               run: |
                   missing_tests=$(for f in $(find src -mindepth 1 -maxdepth 1 -type f -name '*.mts' -exec basename {} .mts ';'); do if ! test -e "tests/${f}.test.js"; then echo "Missing test for src/${f}.mts"; fi; done);
-                  test -s "${missing_tests}" || if ! test -s "${missing_tests}"; then echo "${missing_tests}"; false; fi
+                  test -z "${missing_tests}" || (echo "${missing_tests}"; false)
             - name: compile typescript
               run: tsc
             - name: test
