lint

diff --git a/.github/workflows/push.yaml b/.github/workflows/push.yaml
--- a/.github/workflows/push.yaml
+++ b/.github/workflows/push.yaml
@@ -13,5 +13,5 @@ jobs:
               run: npm run coverage
             - name: check test completeness
               run: |
-                missing_tests=$(for f in $(find src -mindepth 1 -maxdepth 1 -type f -name '*.mts' -exec basename {} .mts ';'); do if ! test -e "tests/${f}.test.js"; then echo "Missing test for src/${f}.mts"; fi; done);
-                if ! test -s "${missing_tests}"; then echo "You are not done, my friend:\n${missing_tests}"; false; fi
+                  missing_tests=$(for f in $(find src -mindepth 1 -maxdepth 1 -type f -name '*.mts' -exec basename {} .mts ';'); do if ! test -e "tests/${f}.test.js"; then echo "Missing test for src/${f}.mts"; fi; done);
+                  if ! test -s "${missing_tests}"; then echo "You are not done, my friend:\n${missing_tests}"; false; fi
